name: Release

on:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Grab branch
        uses: actions/checkout@v1
        with:
          fetch-depth: 100
      
      - name: Packager
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      
      - name: Github Actions
        uses: actions/upload-artifact@v2
        with:
          name: ElvUI_MerathilisUI
          path: .release/*.zip

      - name: Send status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.discord_webhook_url }} # required
          status: ${{ job.status }} # optional, this is the default
          if: always() # or failure() or success()
