name: Release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
       CF_API_KEY: ${{ secrets.CF_API_KEY }}
       GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
       WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Clone Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Retail
        uses: BigWigsMods/packager@master
      - name: Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g classic
      - name: Burning Crusade Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g bcc
      - name: Github Actions
        uses: actions/upload-artifact@v2
        with:
          name: ElvUI_MerathilisUI
          path: .release/*.zip
      - name: Send status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
        if: failure()
